FROM ubuntu
RUN apt update && apt install python3 python3-pip -yy


# ------------------------
# ADD YOUR CODE BETWEEN LINES




# ------------------------

RUN pip3 install -r requirements.txt
CMD ["python3","hello.py"]
EXPOSE 9999
